### ISSUE TITLE
Gyökvonást számító metódus

### ISSUE THREAD

**Issue by FireWolfy89** [FireWolfy89/RFT-Project#2]
Egy gyökvonás számító függvény amely illeszkedik az eddig felépített struktúrára.

**Comment by Patrik960624** [comment]
if (elso === "" || muv === "" || masodik === "") {
        alert("Minden mezőt ki kell tölteni!");
        return;
Ezt a részt majd át kell írnom, mert a gyökvonásnál csak az első szám van kitöltve és egy kivételt be kell hoznom, hogy ezen átmenjen.

**Comment by Patrik960624** [comment]
if(muv === "sqrt" && parseFloat(masodik) === ""){
                alert("Írj egy 0-at a második számhoz, hogy ne legyen üres!")
                return;
            }
Így oldottam meg, hogy ne legyen üres a második szám mező de nem fogja használni a metódus így nem zavar be.
